docs_dir: docs/book
site_dir: docs/html
pages:
    - index.md
    - { Intro: intro.md }
    - Reference:
      - { 'Block Ciphers': block-cipher.md }
      - { 'Encrypting Files': files.md }
      - { 'Hybrid Cryptosystem': hybrid.md }
      - { 'Key Derivation': key-derivation.md }
      - { Passwords: password.md }
      - { 'Public Key Cryptography': public-key.md }
site_name: zend-crypt
site_description: Zend\Crypt
repo_url: 'https://github.com/zendframework/zend-crypt'
copyright: 'Copyright (c) 2016-2017 <a href="http://www.zend.com/">Zend Technologies USA Inc.</a>'
